name: Jekyll Site CI

on:
  push:
    branches:
      - main  # Change as appropriate

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build Jekyll site
        uses: jekyll-action/jekyll-action@v2
        with:
          jekyll_src: '.'
          jekyll_env: 'production'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: './_site'
